### ISSUE TITLE
Move sphere settings to settingsfile ESTIMATE: 5h

### ISSUE THREAD

**Issue by rpkarlsson** [Visualisering/Visualisering-frontend#1]

**Comment by rpkarlsson** [comment]
Do we have a preference as to how to solve this?
I was thinking a settings.json per component? The structure would then become:

``` shell
app
├── components
│   └── sphere
│       ├── settings.json
│       └── sphere.js
└── dataStores
```

Or do we want to move the datastore directly to the components folder also?
Making it:

``` shell
app
├── components
    └── sphere
        ├── dataStore.js
        ├── settings.json
        └── sphere.js
```

     
Im leaning towards the latter. Feels like it would make one single component into one "module" grouping all files into one single location...

Any thoughts? @mw222rs, @sk222sw?

**Comment by fyrkant** [comment]
I think that the "react way" of doing it would just be to expose all settings through props, and keeping it all in one file. A component should be as "stupid" as possible, just take it's props and render what it's supposed to from that. 

I envision a Sphere component being used like this:
`<Sphere lineColor="#b4da55" speed={3} data={data} /*some other props*/ />`

**Comment by rpkarlsson** [comment]
Yes. But how do we organize the files. 
The lineColor or the value 3 being assigned to speed must come from somewhere. In this case the settings.json file right? We want to lift all configuration to an external easy to adjust file.

Each "module" consists of one React component, one datastore, and one settings file. 

Example:

``` javascript
// Read sphere settings from file
// Pseudo code!
const s = file.read("/component/sphere/settings.json");


<Sphere lineColor=s.lineColor speed={s.speed} data={data} /*some other props*/ />

// settings.json would contain
{
 lineColor: "#b4da55",
 speed: 3
};
```

Would it be possible to organize the files in the following manner:

``` shell
app
├── module
    └─ sphere
        ├── dataStore.js
        ├── settings.json
        └── component.js
    └─ matrixer
        ├── dataStore.js
        ├── settings.json
        └── component.js
```

**Comment by fyrkant** [comment]
No it would be passed in from the parent component or the redux store! 

This would be easier if I implemented redux into the app... Give me an hour or two and you'll have a pull request!

**Comment by rpkarlsson** [comment]
I've rearranged the files into what I'm trying to get at in this branch:
https://github.com/rk222ev/Visualisering-frontend/tree/redux

Would something like this be viable. Each frontend module would have its own universe and switching/adding/removing components would be very easy as everything is grouped into one folder under modules.

**Comment by fyrkant** [comment]
Hmm, no I don't think that is the way to do things in a React/redux app. If we need self-contained components we could try going with web components/polymer instead, but I don't really understand why we need it? Maybe we can talk about it more in 10 minutes!

**Comment by fyrkant** [comment]
Maybe close this one too?

**Comment by rpkarlsson** [comment]
Yeah, it feels like its resolved.
