### ISSUE TITLE
Get backend data via web sockets ESTIMATE: 3h

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-frontend#33]
Now its possible to receive initial state from wss://iviz-back.herokuapp.com/ instead of using initial-state.js. The JSON-object is sent to client on connect.

**Comment by fyrkant** [comment]
Renamed issue. 

Initial state is nothing more than description of the starting state of the application and should not be received from the backend. We will receive data form the backend and update the initial state with a new state.

**Comment by fyrkant** [comment]
Also changed estimated time from 1 to 3 hours giving me more time to think through what the best way to implement the connection is.

**Comment by mw222rs** [comment]
PR #45
