### ISSUE TITLE
Add transition animation when looping through visualizations. ESTIMATE: 5h

### ISSUE THREAD

**Issue by fyrkant** [Visualisering/Visualisering-frontend#40]

**Comment by fyrkant** [comment]
I'm having serious issues with this issue. I have already burned 8 hours getting nowhere close to working transition animations - I'm getting super weird twitchy animations and confusing bugs from the spheres - so I think that I will _put a pin in it_ so to say and remove it from this iteration. If the time allows it I might come back to it next week.

Although the animation between route changes has been requested by the customer I think that there are more important features, like creating another visualization, that should be ranked higher. 

Is everybody okay with this?

**Comment by rpkarlsson** [comment]
I think it sound like a good idea. Time is starting to run out..

**Comment by sk222sw** [comment]
I'm okay with that
